### ISSUE TITLE
String[] usage over spaces and dashes

### ISSUE THREAD

**Issue by Curstantine** [IchimakiKasura/kasu.nhentaiapi.js#2]
> If the tag has a space like sole female please add a dash.

Instead of using - to represent a character space and a space to represent a new line, use string[] or simply array of strings and let the module handle the work.

**Comment by IchimakiKasura** [comment]
I made this Function on the first day I made this like on version 1.0.0 I'm still new at Node.js that time (It was just 5 months ago) so It's kinda stuck there since the beginning. I just realized that even without dashes it still do the work. So I'll just remove the dashes on the README.md.
![image](https://user-images.githubusercontent.com/80595346/128489556-5de4ef9e-1898-4aa5-9002-be3a207e8593.png)
![image](https://user-images.githubusercontent.com/80595346/128489594-f568e669-f780-442e-b91a-5c126e9b0f01.png)

String array isn't really necessary because I can just replace the spaces with + because
this is the code to fetch it `${url}search/?q=${string}/`
