### ISSUE TITLE
Deploying fails on heroku on 3.9.3

### ISSUE THREAD

**Issue by nXtremist** [IchimakiKasura/kasu.nhentaiapi.js#5]
Hi,

The latest version fails while deploying on heroku with the following message. Works fine locally on windows.
3.7.9 deploys successfully

```
-----> Installing dependencies
       Installing node modules
       npm ERR! code 2
       npm ERR! path /tmp/build_1b0b1442/node_modules/kasu.nhentaiapi.js
       npm ERR! command failed
       npm ERR! command sh -c md ..\kasuNhentaiJS & echo module.exports = require("kasu.nhentaiapi.js"); > ..\kasuNhentaiJS/index.js
       npm ERR! sh: 1: Syntax error: "(" unexpected
```

**Comment by IchimakiKasura** [comment]
Oh about this problem, I already know this will happen but you can just manually install it by downloading it from [here](https://unpkg.com/browse/kasu.nhentaiapi.js@3.9.3/).

The command fails because the only thing it does is to create a folder named "kasuNhentaiJS" and create a file inside of it.
The reason is to make the require name shorter like instead of this
```js
const nhentaiapi = require("kasu.nhentaiapi.js");
```
its just
```js
const nhentaiapi = require("kasuNhentaiJS");
```
since renaming an NPM package is not allowed.

**Comment by TibixDev** [comment]
I think the best course of action would be to make an entirely new NPM package, because that'd fix the issue, right?
Currently downloading only this package while everything else works with NPM install is incredibly awkward to do even though this library is a nice one and I wanna use it. Could you maybe consider looking into this further?

Thanks.

**Comment by IchimakiKasura** [comment]
> I think the best course of action would be to make an entirely new NPM package, because that'd fix the issue, right? Currently downloading only this package while everything else works with NPM install is incredibly awkward to do even though this library is a nice one and I wanna use it. Could you maybe consider looking into this further?
> 
> Thanks.

The problem here is that my `post-install` command is causing trouble on the heroku because I only tested the command I wrote inn CMD / Batch on Windows.

In any case I'll probably just remove the command and include a batch file in the package.

It will still works since the command only do is to create a folder in the `node_modules` with a name of `kasuNhentaiJS`
so that in your `index.js` you can just require using the `kasuNhentaiJS` instead of the longer `kasu.nhentaiapi.js`

I'll probably make a hotfix later this march since I'm too busy doing important things early this march.
